### ISSUE TITLE
Problematic Project

### ISSUE THREAD

**Issue by Jack-O-Brian** [nabeeeeel/corn-bot#1]
While I eat corn like anyone else, this project is politically wrong. Here's some ways to change this:
1. Implant a code of conduct, to prevent toxic corn people from messing this community: https://raw.githubusercontent.com/pamepeixinho/awesome-list-dev-memes/master/code-of-conduct.md
2. Change the language from Java to something less problematic, like Rust.

- Signed, by Rust

**Comment by nabeeeeel** [comment]
Issue is irrelevant. Corn is a dog not a vegetable, and the language used was Kotlin, not Java.

**Comment by Jack-O-Brian** [comment]
Kotlin is just Java in a different skin. Dogs are also problematic, since they're evil. I refer to [this link](https://www.openbible.info/topics/are_dogs_evil)
And you didn't fix the code of conduct being missing.  You don't want to be cancelled now, do you?
